apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskdemo
  strategy: {}
  template:
    metadata:
      labels:
        app: flaskdemo
    spec:
      containers:
      - image: scottiee/demo-flask-pipeline:latest
        name: flaskdemo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30081  # Specify the desired NodePort value
  selector:
    app: flaskdemo

